services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:0.0
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file:
      - path: .env
    hostname: mariadb
    restart: unless-stopped
    pull_policy: never
    container_name: mariadb
  wordpress:
    build: ./requirements/wordpress
    image: wordpress:0.0
    env_file:
      - path: .env
    volumes:
      - wordpress-data:/var/html/www/wordpress
    hostname: wordpress
    restart: unless-stopped
    pull_policy: never
    depends_on:
      - mariadb
    container_name: wordpress
  nginx:
    ports:
      - 443:443
    volumes:
      - wordpress-data:/var/html/www/wordpress
    build: ./requirements/nginx
    image: nginx:0.0
    hostname: nginx
    restart: unless-stopped
    pull_policy: never
    depends_on:
      - wordpress
      - redis
    container_name: nginx
  redis:
    build: ./requirements/bonus/redis
    image: redis:0.0
    pull_policy: never
    restart: unless-stopped
    container_name: redis
  ftp:
    ports:
      - 21:21
      - 20:20
      - 4000-4005:4000-4005
    build: ./requirements/bonus/ftp
    image: ftp:0.0
    env_file:
      - path: .env
    pull_policy: never
    depends_on:
      - wordpress
    restart: unless-stopped
    container_name: ftp
    volumes:
      - wordpress-data:/var/www/wordpress
  # adminer:
  #   ports:
  #     - 8008:80
  #   build: ./requirements/bonus/adminer
  #   image: adminer:0.0
  #   pull_policy: never
  #   restart: unless-stopped
  #   container_name: adminer
  # cadvisor:
  #   ports:
  #     - 8009:8080
  #   build: ./requirements/bonus/cadvisor
  #   image: cadvisor:0.0
  #   pull_policy: never
  #   restart: unless-stopped
  #   container_name: cadvisor
  # site:
    # ports:
    #   - 8010:81
    # build: ./requirements/bonus/site
    # image: site:0.0
    # pull_policy: never
    # restart: unless-stopped
    # container_name: site
    
volumes:
  mariadb-data:
  wordpress-data: