services:
  mariadb:
    networks:
      - docker-network
    build: ./requirements/mariadb
    image: mariadb:0.0
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - path: .env
    hostname: mariadb
    restart: always
    pull_policy: never
    container_name: mariadb
  wordpress:
    networks:
      - docker-network
    build: ./requirements/wordpress
    image: wordpress:0.0
    env_file:
      - path: .env
    volumes:
      - wordpress:/var/html/www/wordpress
    hostname: wordpress
    restart: always
    pull_policy: never
    depends_on:
      - mariadb
      - redis
    container_name: wordpress
  nginx:
    networks:
      - docker-network
    ports:
      - 443:443
    volumes:
      - wordpress:/var/html/www/wordpress
    build: ./requirements/nginx
    image: nginx:0.0
    hostname: nginx
    restart: always
    pull_policy: never
    depends_on:
      - wordpress
      - redis
    container_name: nginx
  redis:
    networks:
      - docker-network
    build: ./requirements/bonus/redis
    image: redis:0.0
    pull_policy: never
    restart: always
    container_name: redis
  ftp:
    networks:
      - docker-network
    ports:
      - 21:21
      - 20:20
      - 4000-4005:4000-4005
    build: ./requirements/bonus/ftp
    image: ftp:0.0
    env_file:
      - path: .env
    pull_policy: never
    depends_on:
      - wordpress
    restart: always
    container_name: ftp
    volumes:
      - wordpress:/var/html/www/wordpress
  adminer:
    networks:
      - docker-network
    ports:
      - 80:80
    build: ./requirements/bonus/adminer
    image: adminer:0.0
    pull_policy: never
    restart: always
    container_name: adminer
  portainer:
    networks:
      - docker-network
    ports:
      - 9000:9000
    build: ./requirements/bonus/portainer
    image: portainer:0.0
    pull_policy: never
    restart: always
    container_name: portainer
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
      - portainer:/data
  site:
    ports:
      - 81:81
    build: ./requirements/bonus/site
    image: site:0.0
    pull_policy: never
    restart: always
    container_name: site
    
networks:
    docker-network:
      driver: bridge

volumes:
  mariadb:
    name : mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/mariadb'
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/wordpress'
  portainer:
    name: portainer
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/portainer'