services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:0.0
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file:
      - path: .env
        required: true
    hostname: mariadb
    restart: unless-stopped
    pull_policy: never
    container_name: mariadb
  wordpress:
    build: ./requirements/wordpress
    image: wordpress:0.0
    env_file:
      - path: .env
        required: true
    volumes:
      - wordpress-data:/var/html/www/wordpress
    hostname: wordpress
    restart: unless-stopped
    pull_policy: never
    depends_on:
      - mariadb
    container_name: wordpress
  nginx:
    ports:
      - 8000:443
    volumes:
      - wordpress-data:/var/html/www/wordpress
    build: ./requirements/nginx
    image: nginx:0.0
    hostname: nginx
    restart: unless-stopped
    pull_policy: never
    depends_on:
      - wordpress
      - redis

    container_name: nginx
  redis:
    build: ./requirements/bonus/redis
    image: redis:0.0
    pull_policy: never
    restart: unless-stopped
    container_name: redis
  ftp:
    ports:
      - 8001:21
      - 8002:20
    build: ./requirements/bonus/ftp
    image: ftp:0.0
    pull_policy: never
    restart: unless-stopped
    container_name: ftp
    volumes:
      - wordpress-data:/var/html/www/wordpress
    
volumes:
  mariadb-data:
  wordpress-data: