services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:0.0
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file:
      - path: .env
        required: true
    hostname: mariadb
    restart: unless-stopped
    pull_policy: never
  wordpress:
    build: ./requirements/wordpress
    image: wordpress:0.0
    env_file:
      - path: .env
        required: true
    volumes:
      - wordpress-data:/var/html/www/wordpress
    hostname: wordpress
    restart: unless-stopped
    pull_policy: never
    depends_on:
      - mariadb
  nginx:
    ports:
      - 8000:443
    volumes:
      - wordpress-data:/var/html/www/wordpress
    build: ./requirements/nginx
    image: nginx:0.0
    hostname: nginx
    restart: unless-stopped
    pull_policy: never
    depends_on:
      - wordpress

 
    
volumes:
  mariadb-data:
  wordpress-data: